### ISSUE TITLE
Cannot fetch nft

### ISSUE THREAD

**Issue by berk-can** [dabit3/polygon-ethereum-nextjs-marketplace#26]
Hi all, I've setup project as mentioned in README (local setup without changing hardhat config), then I've connected new account from metamask (should I have do something else?) then I've clicked to My Assets, and it thrown this error:

`Uncaught (in promise) Error: call revert exception (method="fetchMyNFTs()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at Logger.makeError (index.js?ffb2:185)
    at Logger.throwError (index.js?ffb2:194)
    at Interface.decodeFunctionResult (interface.js?a807:341)
    at Contract.eval (index.js?f179:288)
    at Generator.next (<anonymous>)
    at fulfilled (index.js?f179:5)`

I am newby on Blockchain part so I dont know if there is something else I should have done, can somebody please direct me

**Comment by vvronskyFX** [comment]
It has to be something with the JsonRPC link in the index.js file or something in our config.js or hardhat.config.js. I'm having the same error and just playing around with the code. No solid solution to share yet. Any support would be appreciated.

**Comment by skimaharvey** [comment]
I had this issue the problem is coming from the deploy.js not printing out the correct NFTMarket contract address as well as the correct NFT contract address...
What you can do is once you have deployed on Mumbai, go to your wallet. Find the transactions and from there you can get the correct contracts addresses and update accordingly your config.js file

**Comment by berk-can** [comment]
@skimaharvey sorry I dont have enough know-how about Mumbai or test networks is there a guideline to follow to make this project run with a test network?

**Comment by hoan27920232** [comment]
@skimaharvey can you be more detail pls

**Comment by hoan27920232** [comment]
@berk-can hey i just figure out why we get this error. It's not our code. I think the problem is the version of libraries we use has changed. Just change the version in package.json exactly like orginal code and paste the package-lock.json from the orginal code to your project then npm i

**Comment by latonet** [comment]
i get the same type of error as berk-can but for fetching market NFTs, i can create NFTs and they show in my dashboard but but not in the market, so i can't test buy/sell. Thanks

**Comment by berk-can** [comment]
@hoan27920232 sorry didnt get what you meant by original code, should I get package.json from a first commit of yours?

**Comment by latonet** [comment]
from the repository i assume

**Comment by latonet** [comment]
@berk-can from the repository i assume

**Comment by latonet** [comment]
hey i just figure out why we get this error. It's not our code. I think the problem is the version of libraries we use has changed. Just change the version in package.json exactly like orginal code and paste the package-lock.json from the orginal code to your project then npm i

@hoan27920232 This doesn't fix the problem, i can still create NFTs and they show in my dashboard but not the marketplace (home page). I got this error again >>> Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.2)

**Comment by latonet** [comment]
I had to add the chainstack RPC and it works now. NFTs are created and listed in dashboard for an account, and listed in the home page as marketplace, however nothing happens  when i click on the Buy button. Thanks

**Comment by berk-can** [comment]
I've installed it from start, started hardhat server, connected metamask and imported account then went into site problem didnt occured again
